// <auto-generated />
namespace MasterClassAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stu_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stu_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111929575_stu_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
